-- Phase 1 Setup SQL — Run in order
-- Generated by ChatGPT, verified by Claude, Feb 24 2026

-- STEP 1: Create region-mapped earthquake table
CREATE OR REPLACE TABLE `sentinel_groundtruth.master_earthquakes_mapped` AS
WITH normalized AS (
  SELECT
    event_id, time, DATE(time) AS day,
    CASE WHEN longitude >= 180 THEN longitude - 360
         WHEN longitude < -180 THEN longitude + 360
         ELSE longitude END AS lon_norm,
    CASE WHEN latitude > 90 THEN 90
         WHEN latitude < -90 THEN -90
         ELSE latitude END AS lat_norm,
    depth_km, magnitude, magnitude_type, place, status,
    tsunami, sig, net, updated, url, src, ingested_at
  FROM `sentinel_groundtruth.master_earthquakes`
  WHERE latitude IS NOT NULL AND longitude IS NOT NULL AND magnitude IS NOT NULL
),
gridded AS (
  SELECT *,
    CAST(FLOOR(lat_norm / 10.0) * 10 AS INT64) AS lat_bucket,
    CAST(FLOOR(lon_norm / 10.0) * 10 AS INT64) AS lon_bucket
  FROM normalized
)
SELECT event_id, time, day, lat_norm AS latitude, lon_norm AS longitude,
  depth_km, magnitude, magnitude_type, place, status, tsunami, sig, net,
  updated, url, src, ingested_at,
  CONCAT(CAST(lat_bucket AS STRING), '_', CAST(lon_bucket AS STRING)) AS region_key
FROM gridded;

-- STEP 2: Create daily earthquake features with labels
CREATE OR REPLACE TABLE `sentinel_groundtruth.eq_features_daily` AS
WITH daily AS (
  SELECT DATE(time) AS day, region_key,
    COUNTIF(magnitude >= 4.0) AS count_m4,
    COUNTIF(magnitude >= 5.0) AS count_m5,
    COUNTIF(magnitude >= 6.0) AS count_m6,
    COUNTIF(magnitude >= 7.0) AS count_m7,
    MAX(magnitude) AS max_mag
  FROM `sentinel_groundtruth.master_earthquakes_mapped`
  GROUP BY day, region_key
),
rolled AS (
  SELECT d.*,
    SUM(count_m4) OVER w7  AS count_m4_7d,
    SUM(count_m5) OVER w7  AS count_m5_7d,
    SUM(count_m6) OVER w7  AS count_m6_7d,
    SUM(count_m7) OVER w7  AS count_m7_7d,
    MAX(max_mag)  OVER w7  AS max_mag_7d,
    SUM(count_m4) OVER w30 AS count_m4_30d,
    SUM(count_m5) OVER w30 AS count_m5_30d,
    SUM(count_m6) OVER w30 AS count_m6_30d,
    SUM(count_m7) OVER w30 AS count_m7_30d,
    MAX(max_mag)  OVER w30 AS max_mag_30d
  FROM daily d
  WINDOW
    w7  AS (PARTITION BY region_key ORDER BY day ROWS BETWEEN 6 PRECEDING AND CURRENT ROW),
    w30 AS (PARTITION BY region_key ORDER BY day ROWS BETWEEN 29 PRECEDING AND CURRENT ROW)
),
labels AS (
  SELECT dr.day, dr.region_key,
    IF(EXISTS (
      SELECT 1 FROM `sentinel_groundtruth.master_earthquakes_mapped` e
      WHERE e.region_key = dr.region_key
        AND e.day BETWEEN DATE_ADD(dr.day, INTERVAL 1 DAY) AND DATE_ADD(dr.day, INTERVAL 7 DAY)
        AND e.magnitude >= 6.0
    ), 1, 0) AS y_m60_next7d
  FROM (SELECT DISTINCT day, region_key FROM daily) dr
)
SELECT r.*, l.y_m60_next7d
FROM rolled r
JOIN labels l USING (day, region_key);

-- STEP 3: Create env_daily skeleton
CREATE OR REPLACE TABLE `sentinel_features.env_daily` AS
WITH days AS (
  SELECT DISTINCT day FROM `sentinel_groundtruth.eq_features_daily`
)
SELECT day,
  CAST(NULL AS FLOAT64) AS kp_max,
  CAST(NULL AS FLOAT64) AS kp_mean,
  CAST(NULL AS FLOAT64) AS sw_speed_mean,
  CAST(NULL AS FLOAT64) AS sw_density_mean,
  CAST(NULL AS FLOAT64) AS sw_bz_min,
  CAST(NULL AS FLOAT64) AS xray_max,
  CAST(NULL AS FLOAT64) AS electron_flux_max,
  CAST(NULL AS INT64)   AS has_cme,
  CAST(NULL AS INT64)   AS has_sep
FROM days;

-- STEP 4: Create phase1_dataset view
CREATE OR REPLACE VIEW `sentinel_eval.phase1_dataset` AS
SELECT
  e.day, e.region_key, e.y_m60_next7d,
  e.count_m4, e.count_m5, e.count_m6, e.count_m7, e.max_mag,
  e.count_m4_7d, e.count_m5_7d, e.count_m6_7d, e.count_m7_7d, e.max_mag_7d,
  e.count_m4_30d, e.count_m5_30d, e.count_m6_30d, e.count_m7_30d, e.max_mag_30d,
  d.kp_max, d.kp_mean, d.sw_speed_mean, d.sw_density_mean, d.sw_bz_min,
  d.xray_max, d.electron_flux_max, d.has_cme, d.has_sep,
  CASE
    WHEN e.day BETWEEN DATE '2001-01-01' AND DATE '2018-12-31' THEN 'train'
    WHEN e.day BETWEEN DATE '2019-01-01' AND DATE '2022-12-31' THEN 'validate'
    WHEN e.day BETWEEN DATE '2023-01-01' AND DATE '2026-12-31' THEN 'test'
    ELSE 'out_of_range'
  END AS split
FROM `sentinel_groundtruth.eq_features_daily` e
LEFT JOIN `sentinel_features.env_daily` d ON d.day = e.day;
